---
- hosts: rmp
  serial: 1
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - { role: apigee-opdk-server-self, server_type: 'router' }
  - { role: apigee-opdk-server-self, server_type: 'mp' }

- hosts: pg
  serial: 1
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - { role: apigee-opdk-server-self, server_type: 'ps' }

- hosts: qpid
  serial: 1
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - { role: apigee-opdk-server-self, server_type: 'qs' }

- hosts: ms
  serial: 1
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - { role: apigee-opdk-server-self, server_type: 'ms' }

